# -*- coding: utf-8 -*-
"""06-01 PDFLoader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zfpNxwM8sbeZMFULOWl1Dwtf1LX8k5h
"""

FILE_PATH = 'C:/Users/박용민/OneDrive/바탕 화면/비트컴퓨터/SPRI_AI_Brief_2023년12월호_F.pdf'

def show_metadata(docs):
  if docs:
    print('[metadata]')
    print(list(docs[0].metadata.keys()))
    print('\n[exaples]')
    max_key_length = max(len(k) for k in docs[0].metadata.keys())
    for k, v in docs[0].metadata.items():
      print(f'{k:<{max_key_length}} : {v}')

#pip install pypdf langchain_community

from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader(FILE_PATH)
docs = loader.load()

print(docs[10].page_content[:300])

show_metadata(docs)

#pip install pymupdf

from langchain_community.document_loaders import PyMuPDFLoader
loader = PyMuPDFLoader(FILE_PATH)
docs = loader.load()

print(docs[10].page_content[:300])

show_metadata(docs)

#pip install pypdfium2

from langchain_community.document_loaders import PyPDFium2Loader
loader = PyPDFium2Loader(FILE_PATH)
docs = loader.load()



#pip install pdfminer.six

from langchain_community.document_loaders import PDFMinerLoader

loader = PDFMinerLoader(FILE_PATH)

docs = loader.load()

from langchain_community.document_loaders import PDFMinerPDFasHTMLLoader

loader = PDFMinerPDFasHTMLLoader(FILE_PATH)

docs = loader.load()

print(docs[0].page_content[:1000])