# -*- coding: utf-8 -*-
"""06.11_DirectoryLoader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Dofm0fajzh9Tnonb4nqx53yUXXJepTG
"""

import os

print(os.getcwd())

!pip install langchain_community
!pip install unstructured

from langchain_community.document_loaders import DirectoryLoader

loader = DirectoryLoader("/content/sample_data", glob="*.md")

docs = loader.load()

len(docs)

print(docs[0].page_content[:100])

!pip install tqdm

loader = DirectoryLoader(
    "./", glob="**/*.md", show_progress=True
)
docs = loader.load()

loader = DirectoryLoader(
    "./", glob="**/*.md", use_multithreading=True
)
docs = loader.load()

from langchain_community.document_loaders import TextLoader

loader = DirectoryLoader("/content/", glob="**/*.md", loader_cls=TextLoader)
docs = loader.load()

print(docs[0].page_content)

from langchain_community.document_loaders import PythonLoader

loader = DirectoryLoader("./", glob="**/*.py", loader_cls=PythonLoader)

docs = loader.load()
docs

from langchain_community.document_loaders import TextLoader

loader = DirectoryLoader("/content/", glob="**/*.Text", loader_cls=TextLoader)
docs = loader.load()

docs

from langchain_community.document_loaders import TextLoader

loader = DirectoryLoader("/content/", glob="**/*.md", loader_cls=TextLoader)
docs = loader.load()

docs

from langchain_community.document_loaders import TextLoader

loader = DirectoryLoader("/content/", glob="**/*.py", loader_cls=TextLoader)
docs = loader.load()

docs