# -*- coding: utf-8 -*-
"""20241227_1_characterTextsplit_박용민.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNHqdbLKxqS5wOKE5DOwM4yzUelvEqvz
"""

with open("/content/data/자기소개서.txt", encoding="euc-kr") as f:
  file = f.read()

print(file[:500])

from langchain_text_splitters import CharacterTextSplitter

text_splitters = CharacterTextSplitter(
    separator='\n',
    chunk_size=210,
    chunk_overlap=0,
    length_function=len,
)

texts = text_splitters.create_documents([file])
print(len(texts[0].page_content))
print(texts[0])

metadatas = [
    {'document': 1},
    {'document': 2},
]
documents = text_splitters.create_documents(
    [
        file,
        file,
    ],
    metadatas=metadatas,

)
print(documents[0])

len(documents)

documents[1].metadata

text_splitters.split_text(file)[0]

































