# -*- coding: utf-8 -*-
"""Untitled136.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wPAnrscw0MdL73SM8AFbHm_58s7hQ2Fr
"""

import os

api_key = ''
os.environ['OPENAI_API_KEY'] = api_key

from datetime import datetime

datetime.now().strftime("%B %d")

def get_today():
  return datetime.now().strftime("%B %d")

pip install -q langchain_teddynote langchain_openai langchain_core

from langchain_teddynote.messages import stream_response
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
prompt = PromptTemplate(
    template="오늘의 날짜는 {today}입니다. 오늘이 생일인 유명인 {n}명을 나열해주세요. 생년월일을 표기해주세요.",
    input_variables=["today", "n"],  # 필요한 입력 변수
)

prompt

model = ChatOpenAI(
    model='gpt-3.5-turbo',
    max_tokens=2048,
    temperature=0.1,
)

prompt_partial = prompt.partial(n="5")

final_prompt = prompt_partial.format(today=get_today())
print("Generated Prompt:", final_prompt)

chain = prompt_partial | model

response = chain.invoke({"today": get_today()}).content
print("Response:", response)