# -*- coding: utf-8 -*-
"""키확인.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnKukYB3p_Yaj0Ib6lIM4SB2wKk8F3ZA

# 1. 키확인
"""

import os

api_key = ''
os.environ['OPENAI_API_KEY'] = api_key

from dotenv import load_dotenv

load_dotenv()

"""# 2. 키 유효성 확인"""

print(f'[API KEY]\n{api_key[:-15]}' + '*' * 15)